
exports.BYCRYPT_LENGTH = 12;
exports.REMEMBER_EXPIRE_TIME = '168h';
exports.EXPIRE_TIME = '48h';
exports.TOKEN_EXPIRED_CODE = 'TOKEN_EXPIRED';
exports.USER_STATUS_TYPE = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE'
}